spring.application.name=Camera-access

# MySQL Database Settings
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/Camera_access
spring.datasource.username=root
spring.datasource.password=WASD@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# H2 Console ko disable kar dein (Kyunki ab MySQL use ho raha hai)
spring.h2.console.enabled=false